// kanban-nextjs/src/components/CardList.tsx
"use client";

import { useDroppable } from "@dnd-kit/core";
import {
  SortableContext,
  verticalListSortingStrategy,
} from "@dnd-kit/sortable";
import type { BoardDetails, UsersList, TagsList, BoardCard } from "@/lib/api";
import { Card } from "./Card";

export function CardList({
  list,
  allUsers,
  allTags,
  onCardUpdate,
}: {
  list: BoardDetails["lists"][number];
  allUsers: UsersList;
  allTags: TagsList;
  onCardUpdate?: (cardId: string, updates: Partial<BoardCard>) => void;
}) {
  const { setNodeRef, isOver, over } = useDroppable({
    id: `list-${list.id}`,
  });

  const cardIds = list.cards.map((card) => card.id);

  // Check if we're over this list OR over any card in this list
  const isOverThisList = isOver || (over && cardIds.includes(over.id as string));

  return (
    <section className="card bg-base-200 dark:bg-base-300 min-w-[20rem] shadow-xl">
      <div className="card-body gap-4">
        <header className="flex items-center justify-between">
          <h2 className="card-title text-base-content">{list.title}</h2>
          <div className="badge badge-primary badge-outline badge-lg shadow">
            {list.cards.length} cards
          </div>
        </header>

        <div
          ref={setNodeRef}
          className={`min-h-[200px] transition-all duration-200 rounded-lg ${
            isOverThisList
              ? "ring-4 ring-primary ring-offset-2 bg-primary/5 scale-[1.02]"
              : ""
          }`}
        >
          {list.cards.length === 0 ? (
            <div className="alert alert-info text-sm">
              <span>No cards yet</span>
            </div>
          ) : (
            <SortableContext items={cardIds} strategy={verticalListSortingStrategy}>
              <div className="space-y-3">
                {list.cards.map((card) => (
                  <Card
                    key={card.id}
                    card={card}
                    allUsers={allUsers}
                    allTags={allTags}
                    onCardUpdate={onCardUpdate}
                  />
                ))}
              </div>
            </SortableContext>
          )}
        </div>
      </div>
    </section>
  );
}

// kanban-tanstack-solid/src/components/CardList.tsx
import { For } from "solid-js";
import type { BoardDetails, UsersList, TagsList, BoardCard } from "../lib/api";
import { Card } from "./Card";
import { createDroppable } from "@thisbeyond/solid-dnd";

export function CardList(props: {
  list: BoardDetails["lists"][number];
  allUsers: UsersList;
  allTags: TagsList;
  onCardUpdate?: (cardId: string, updates: Partial<BoardCard>) => void;
  onCardDelete?: (cardId: string) => void;
}) {
  // Create a droppable zone for this list
  const droppable = createDroppable(`list-${props.list.id}`);

  return (
    <section class="card bg-base-200 dark:bg-base-300 min-w-[20rem] shadow-xl">
      <div class="card-body gap-4">
        <header class="flex items-center justify-between">
          <h2 class="card-title text-base-content">{props.list.title}</h2>
          <div class="badge badge-primary badge-outline badge-lg shadow">
            {props.list.cards.length} cards
          </div>
        </header>

        <div
          ref={droppable}
          class="min-h-[200px] transition-all duration-200 rounded-lg"
          classList={{
            "ring-2 ring-primary ring-opacity-50": droppable.isActiveDroppable,
          }}
        >
          {props.list.cards.length === 0 ? (
            <div class="alert alert-info text-sm">
              <span>No cards yet</span>
            </div>
          ) : (
            <div class="space-y-3">
              <For each={props.list.cards}>
                {(card) => (
                  <Card
                    card={card}
                    allUsers={props.allUsers}
                    allTags={props.allTags}
                    onCardUpdate={props.onCardUpdate}
                    onCardDelete={props.onCardDelete}
                  />
                )}
              </For>
            </div>
          )}
        </div>
      </div>
    </section>
  );
}
