// kanban-nextjs/src/components/modals/CommentModal.tsx
"use client";

import { useState } from "react";
import type { BoardCard, UsersList } from "@/lib/api";
import { addComment } from "@/lib/actions";

export function CommentModal({
  card,
  users,
  isOpen,
  onClose,
  onCommentAdd,
}: {
  card: BoardCard;
  users: UsersList;
  isOpen: boolean;
  onClose: () => void;
  onCommentAdd?: (comment: { userId: string; text: string }) => void;
}) {
  const [selectedUserId, setSelectedUserId] = useState(users[0]?.id || "");

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const form = e.currentTarget;
    const formData = new FormData(form);

    const userId = formData.get("userId") as string;
    const text = formData.get("text") as string;

    // Optimistically update the UI
    if (onCommentAdd) {
      onCommentAdd({ userId, text });
    }

    onClose();

    // Reset form
    form.reset();
    setSelectedUserId(users[0]?.id || "");

    // Persist to server in background
    await addComment(formData);
  };

  if (!isOpen) return null;

  return (
    <dialog
      className="modal modal-open !mt-0"
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
    >
      <div className="modal-backdrop bg-black/70" />
      <div className="modal-box bg-base-200 dark:bg-base-300 max-w-2xl">
        <button
          type="button"
          className="btn btn-sm btn-circle btn-ghost absolute right-2 top-2"
          onClick={onClose}
        >
          ✕
        </button>

        <h3 className="font-bold text-lg mb-4">Comments</h3>

        {/* Existing Comments */}
        <div className="mb-6 max-h-96 overflow-y-auto">
          {card.comments.length === 0 ? (
            <div className="text-center py-8 text-base-content/60">
              No comments yet. Be the first to add one!
            </div>
          ) : (
            <div className="space-y-3">
              {card.comments.map((comment) => {
                const user = users.find((u) => u.id === comment.userId);
                return (
                  <div
                    key={comment.id}
                    className="bg-base-100 dark:bg-base-200 rounded-lg p-4"
                  >
                    <div className="flex items-center gap-2 mb-2">
                      <span className="font-semibold text-base-content">
                        {user?.name || "Unknown"}
                      </span>
                      <span className="text-xs text-base-content/50">
                        {new Date(comment.createdAt).toLocaleDateString()}
                      </span>
                    </div>
                    <p className="text-sm text-base-content/80">{comment.text}</p>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        {/* Add Comment Form */}
        <form onSubmit={handleSubmit}>
          <input type="hidden" name="cardId" value={card.id} />

          <div className="form-control w-full">
            <label className="label">
              <span className="label-text">Comment as</span>
            </label>
            <select
              name="userId"
              className="select select-bordered w-full"
              value={selectedUserId}
              onChange={(e) => setSelectedUserId(e.currentTarget.value)}
            >
              {users.map((user) => (
                <option key={user.id} value={user.id}>
                  {user.name}
                </option>
              ))}
            </select>
          </div>

          <div className="form-control w-full mt-4">
            <label className="label">
              <span className="label-text">Your comment</span>
            </label>
            <textarea
              name="text"
              className="textarea textarea-bordered h-24 w-full"
              placeholder="Write your comment..."
              required
            />
          </div>

          <div className="modal-action">
            <button type="button" className="btn btn-ghost" onClick={onClose}>
              Close
            </button>
            <button type="submit" className="btn btn-primary">
              Add Comment
            </button>
          </div>
        </form>
      </div>
    </dialog>
  );
}

// kanban-tanstack-solid/src/components/modals/CommentModal.tsx
import type { BoardCard, UsersList } from "@/lib/api";
import { addComment } from "../../utils/api";
import { createSignal, Show } from "solid-js";

export function CommentModal(props: {
  card: BoardCard;
  users: UsersList;
  isOpen: boolean;
  onClose: () => void;
  onCommentAdd?: (comment: { userId: string; text: string }) => void;
}) {
  const [selectedUserId, setSelectedUserId] = createSignal(
    props.users[0]?.id || ""
  );

  const handleSubmit = async (e: SubmitEvent) => {
    e.preventDefault();
    const form = e.currentTarget as HTMLFormElement;
    const formData = new FormData(form);

    const userId = formData.get("userId") as string;
    const text = formData.get("text") as string;

    // Optimistically update the UI
    if (props.onCommentAdd) {
      props.onCommentAdd({ userId, text });
    }

    props.onClose();

    // Reset form
    form.reset();
    setSelectedUserId(props.users[0]?.id || "");

    // Persist to server in background
    await addComment({
      data: {
        cardId: props.card.id,
        userId,
        text,
      },
    });
  };

  return (
    <Show when={props.isOpen}>
      <dialog
        class="modal modal-open !mt-0"
        onClick={(e) => {
          if (e.target === e.currentTarget) props.onClose();
        }}
      >
        <div class="modal-backdrop bg-black/70" />
        <div class="modal-box bg-base-200 dark:bg-base-300 max-w-2xl">
          <button
            type="button"
            class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2"
            onClick={props.onClose}
          >
            ✕
          </button>

          <h3 class="font-bold text-lg mb-4">Comments</h3>

          {/* Existing Comments */}
          <div class="mb-6 max-h-96 overflow-y-auto">
            {props.card.comments.length === 0 ? (
              <div class="text-center py-8 text-base-content/60">
                No comments yet. Be the first to add one!
              </div>
            ) : (
              <div class="space-y-3">
                {props.card.comments.map(
                  (comment: {
                    id: string;
                    userId: string;
                    text: string;
                    createdAt: Date;
                  }) => {
                    const user = props.users.find(
                      (u: { id: string; name: string }) =>
                        u.id === comment.userId
                    );
                    return (
                      <div class="bg-base-100 dark:bg-base-200 rounded-lg p-4">
                        <div class="flex items-center gap-2 mb-2">
                          <span class="font-semibold text-base-content">
                            {user?.name || "Unknown"}
                          </span>
                          <span class="text-xs text-base-content/50">
                            {new Date(comment.createdAt).toLocaleDateString()}
                          </span>
                        </div>
                        <p class="text-sm text-base-content/80">
                          {comment.text}
                        </p>
                      </div>
                    );
                  }
                )}
              </div>
            )}
          </div>

          {/* Add Comment Form */}
          <form onSubmit={handleSubmit}>
            <input type="hidden" name="cardId" value={props.card.id} />

            <div class="form-control w-full">
              <label class="label">
                <span class="label-text">Comment as</span>
              </label>
              <select
                name="userId"
                class="select select-bordered w-full"
                value={selectedUserId()}
                onChange={(e) => setSelectedUserId(e.currentTarget.value)}
              >
                {props.users.map((user: { id: string; name: string }) => (
                  <option value={user.id}>{user.name}</option>
                ))}
              </select>
            </div>

            <div class="form-control w-full mt-4">
              <label class="label">
                <span class="label-text">Your comment</span>
              </label>
              <textarea
                name="text"
                class="textarea textarea-bordered h-24 w-full"
                placeholder="Write your comment..."
                required
              />
            </div>

            <div class="modal-action">
              <button
                type="button"
                class="btn btn-ghost"
                onClick={props.onClose}
              >
                Close
              </button>
              <button type="submit" class="btn btn-primary">
                Add Comment
              </button>
            </div>
          </form>
        </div>
      </dialog>
    </Show>
  );
}
