// src/components/modals/AddBoardModal.tsx
import { Show } from "solid-js";
import { createBoard } from "~/api/board-actions";

export function AddBoardModal(props: {
  isOpen: boolean;
  onClose: () => void;
  onBoardAdd?: (board: { title: string; description: string | null }) => void;
}) {
  const handleSubmit = async (e: Event) => {
    e.preventDefault();
    const form = e.target as HTMLFormElement;
    const formData = new FormData(form);

    const title = formData.get("title") as string;
    const description = formData.get("description") as string;

    // Optimistically update the UI
    if (props.onBoardAdd) {
      props.onBoardAdd({
        title,
        description: description || null,
      });
    }

    props.onClose();

    // Reset form
    form.reset();

    // Persist to server in background
    await createBoard(formData);
  };

  return (
    <Show when={props.isOpen}>
      <dialog
        class="modal modal-open"
        onClick={(e) => {
          if (e.target === e.currentTarget) props.onClose();
        }}
      >
        <div class="modal-backdrop bg-black/70" />
        <div class="modal-box bg-base-200 dark:bg-base-300">
          <form method="dialog" onSubmit={handleSubmit}>
            <button
              type="button"
              class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2"
              onClick={props.onClose}
            >
              ✕
            </button>
            <h3 class="font-bold text-lg mb-4">Add New Board</h3>

            <div class="form-control w-full mb-4">
              <label class="label">
                <span class="label-text">Title</span>
              </label>
              <input
                type="text"
                name="title"
                class="input input-bordered w-full"
                placeholder="Enter board title"
                required
              />
            </div>

            <div class="form-control w-full mb-4">
              <label class="label">
                <span class="label-text">Description</span>
              </label>
              <textarea
                name="description"
                class="textarea textarea-bordered h-24 w-full"
                placeholder="Enter board description (optional)"
              />
            </div>

            <div class="modal-action">
              <button
                type="button"
                class="btn btn-ghost"
                onClick={props.onClose}
              >
                Cancel
              </button>
              <button type="submit" class="btn btn-primary">
                Add Board
              </button>
            </div>
          </form>
        </div>
      </dialog>
    </Show>
  );
}

// kanban-tanstack/src/components/AddBoardModal.tsx
import { useState } from "react";
import { createBoard } from "../utils/api";
import { useRouter } from "@tanstack/react-router";

export function AddBoardModal({
  onBoardAdd,
}: {
  onBoardAdd?: (board: { id: string; title: string; description: string | null }) => void;
}) {
  const [isOpen, setIsOpen] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const router = useRouter();

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const form = e.currentTarget;
    const formData = new FormData(form);

    setError(null);
    setIsSubmitting(true);

    try {
      const title = formData.get("title") as string;
      const description = formData.get("description") as string;

      // Wait for server response to get the real ID
      const result = await createBoard({
        data: {
          title,
          description: description || null
        }
      });

      if (!result.success) {
        setError(result.error || "An error occurred");
        setIsSubmitting(false);
        return;
      }

      // Update UI with server-generated ID
      if (onBoardAdd && result.data) {
        onBoardAdd({
          id: result.data.id,
          title: result.data.title,
          description: result.data.description ?? null,
        });
      }

      setIsOpen(false);
      form.reset();
      router.invalidate();
    } catch {
      setError("An unexpected error occurred. Please try again.");
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <>
      <button
        type="button"
        className="btn btn-primary"
        onClick={() => setIsOpen(true)}
      >
        Add Board
      </button>

      {isOpen && (
        <dialog
          className="modal modal-open !mt-0"
          onClick={(e) => {
            if (e.target === e.currentTarget) setIsOpen(false);
          }}
        >
          <div className="modal-backdrop bg-black/70" />
          <div className="modal-box bg-base-200 dark:bg-base-300">
            <form method="dialog" onSubmit={handleSubmit}>
              <button
                type="button"
                className="btn btn-sm btn-circle btn-ghost absolute right-2 top-2"
                onClick={() => setIsOpen(false)}
              >
                ✕
              </button>
              <h3 className="font-bold text-lg mb-4">Add New Board</h3>

              {error && (
                <div className="alert alert-error mb-4">
                  <span>{error}</span>
                </div>
              )}

              <div className="form-control w-full mb-4">
                <label className="label">
                  <span className="label-text">Title</span>
                </label>
                <input
                  type="text"
                  name="title"
                  className="input input-bordered w-full"
                  placeholder="Enter board title"
                  required
                  disabled={isSubmitting}
                />
              </div>

              <div className="form-control w-full mb-4">
                <label className="label">
                  <span className="label-text">Description</span>
                </label>
                <textarea
                  name="description"
                  className="textarea textarea-bordered h-24 w-full"
                  placeholder="Enter board description (optional)"
                  disabled={isSubmitting}
                />
              </div>

              <div className="modal-action">
                <button
                  type="button"
                  className="btn btn-ghost"
                  onClick={() => setIsOpen(false)}
                  disabled={isSubmitting}
                >
                  Cancel
                </button>
                <button type="submit" className="btn btn-primary" disabled={isSubmitting}>
                  {isSubmitting ? "Adding..." : "Add Board"}
                </button>
              </div>
            </form>
          </div>
        </dialog>
      )}
    </>
  );
}
