// kanban-nuxt/pages/board/[id].vue
<script setup lang="ts">
// Lazy load heavy dependencies with explicit chunk names
const draggable = defineAsyncComponent({
  loader: () => import('vuedraggable'),
})
const BoardOverview = defineAsyncComponent({
  loader: () => import('~/components/BoardOverview.vue'),
})
const Card = defineAsyncComponent({
  loader: () => import('~/components/Card.vue'),
})
const AddCardModal = defineAsyncComponent({
  loader: () => import('~/components/AddCardModal.vue'),
})

import { useAutoAnimate } from '@formkit/auto-animate/vue'
import type { Tag, User, Comment } from '../../drizzle/schema'

interface BoardCard {
  id: string
  title: string
  description: string | null
  assigneeId: string | null
  position: number
  completed: boolean
  tags: Tag[]
  comments: Comment[]
}

interface BoardList {
  id: string
  title: string
  cards: BoardCard[]
}

interface BoardDetails {
  board: {
    id: string
    title: string
    description: string | null
  }
  lists: BoardList[]
  users: User[]
  tags: Tag[]
}

const route = useRoute()
const boardId = route.params.id as string

const { $fetch } = useNuxtApp()

const { data: initialBoard, refresh } = await useAsyncData(
  () => `board-${boardId}`,
  () => $fetch<BoardDetails>(`/api/boards/${boardId}`),
  { server: true }
)

// Local mutable copy for optimistic updates
const board = ref<BoardDetails | null>(initialBoard.value)

// Sync local state with server data when initialBoard changes
watch(initialBoard, (newBoard) => {
  board.value = newBoard
})

const showAddCardModal = ref(false)
const dragOverListId = ref<string | null>(null)
const draggedCard = ref<{ id: string; fromListId: string } | null>(null)

// Auto-animate for smooth transitions
const [listAnimateRef] = useAutoAnimate()

function onDragStart(listId: string, cardId: string) {
  draggedCard.value = { id: cardId, fromListId: listId }
}

function onDragOver(listId: string) {
  dragOverListId.value = listId
}

function onDragLeave() {
  dragOverListId.value = null
}

async function onDragEnd(listId: string, event: any) {
  dragOverListId.value = null

  if (!board.value || !draggedCard.value) {
    return
  }

  const { fromListId, id: cardId } = draggedCard.value
  draggedCard.value = null

  const { oldIndex, newIndex } = event
  if (oldIndex === newIndex && fromListId === listId) return

  try {
    const response = await $fetch('/api/cards/move', {
      method: 'POST',
      body: {
        cardId,
        sourceListId: fromListId,
        targetListId: listId,
        newPosition: newIndex,
      },
    })

    if (response?.success) {
      await refresh()
    }
  } catch (error) {
    await refresh()
  }
}

// Handle optimistic card updates
function handleCardUpdate(cardId: string, updates: Partial<BoardCard>) {
  if (!board.value) return

  const updatedLists = board.value.lists.map((list) => ({
    ...list,
    cards: list.cards.map((card) =>
      card.id === cardId ? { ...card, ...updates } : card
    ),
  }))

  board.value = {
    ...board.value,
    lists: updatedLists,
  }
}

// Handle card creation with server-generated ID
async function handleCardAdd(cardData: {
  id: string
  title: string
  description: string | null
  assigneeId: string | null
  tagIds: string[]
}) {
  showAddCardModal.value = false
  await refresh()
}
</script>

<template>
  <main
    v-if="board"
    class="w-full p-8 space-y-10 rounded-3xl bg-base-100 dark:bg-base-200 shadow-xl"
  >
    <div class="breadcrumbs text-sm">
      <ul>
        <li>
          <NuxtLink to="/" class="link link-hover">Boards</NuxtLink>
        </li>
        <li>
          <span class="text-base-content/60">{{ board.board.title }}</span>
        </li>
      </ul>
    </div>

    <div class="space-y-8">
      <BoardOverview :data="board" />

      <div class="flex justify-start mb-4">
        <button
          type="button"
          class="btn btn-primary"
          @click="showAddCardModal = true"
        >
          Add Card
        </button>
      </div>

      <section class="flex gap-7 overflow-x-auto pb-8">
        <div
          v-if="board.lists.length === 0"
          class="card bg-base-200 dark:bg-base-300 shadow-xl w-full max-w-md mx-auto"
        >
          <div class="card-body items-center text-center">
            <h2 class="card-title text-secondary">No lists yet</h2>
            <p class="text-base-content/60">
              Add a list to begin organizing work on this board.
            </p>
          </div>
        </div>

        <article
          v-for="list in board.lists"
          :key="list.id"
          class="card bg-base-200 dark:bg-base-300 min-w-[20rem] shadow-xl"
        >
          <div class="card-body gap-4">
            <header class="flex items-center justify-between">
              <h2 class="card-title text-base-content">{{ list.title }}</h2>
              <div class="badge badge-primary badge-outline badge-lg shadow">
                {{ list.cards.length }} cards
              </div>
            </header>

            <draggable
              v-model="list.cards"
              item-key="id"
              :group="{ name: 'cards', pull: true, put: true }"
              :class="[
                'min-h-[200px] transition-all duration-200',
                dragOverListId === list.id
                  ? 'ring-4 ring-primary ring-offset-2 bg-primary/5 scale-[1.02]'
                  : ''
              ]"
              @start="onDragStart(list.id, $event.item?.__draggable_context?.element?.id ?? '')"
              @end="onDragEnd(list.id, $event)"
              @dragover="onDragOver(list.id)"
              @dragleave="onDragLeave"
            >
              <template #item="{ element }">
                <div :ref="listAnimateRef" class="space-y-3">
                  <Card
                    :card="element"
                    :users="board.users"
                    :all-users="board.users"
                    :all-tags="board.tags"
                    @card-update="handleCardUpdate"
                  />
                </div>
              </template>
            </draggable>
            <div
              v-if="list.cards.length === 0"
              class="alert alert-info text-sm"
            >
              <span>No cards yet</span>
            </div>
          </div>
        </article>
      </section>
    </div>

    <AddCardModal
      v-if="showAddCardModal"
      :board-id="board.board.id"
      :users="board.users"
      :tags="board.tags"
      @close="showAddCardModal = false"
      @card-add="handleCardAdd"
    />
  </main>

  <main
    v-else
    class="w-full p-8 space-y-10 rounded-3xl bg-base-100 dark:bg-base-200 shadow-xl"
  >
    <div class="flex justify-center py-16">
      <span
        class="loading loading-spinner loading-lg text-primary"
        aria-label="Loading board"
      />
    </div>
  </main>
</template>

// src/routes/board/[id].tsx
import {
  createAsync,
  useParams,
  A,
  type RouteDefinition,
} from "@solidjs/router";
import { For, Show, createSignal, createEffect } from "solid-js";
import { fetchBoard, listUsers, listTags } from "~/api";
import type {
  BoardCard,
  BoardDetails,
  UsersList,
  TagsList,
} from "~/api/boards";
import { BoardOverview } from "~/components/BoardOverview";
import { CardList } from "~/components/CardList";
import { DragDropBoard } from "~/components/DragDropBoard";
import { AddCardModal } from "~/components/modals/AddCardModal";
import { useBoardDragDrop } from "~/lib/drag-drop/hooks";

function CardListFallback() {
  return (
    <div class="card bg-base-200 dark:bg-base-300 shadow-xl w-full max-w-md mx-auto">
      <div class="card-body items-center text-center">
        <h2 class="card-title text-secondary">No lists yet</h2>
        <p class="text-base-content/60">
          Add a list to begin organizing work on this board.
        </p>
      </div>
    </div>
  );
}

export const route = {
  preload({ params }) {
    fetchBoard({ id: params.id });
    listUsers();
    listTags();
  },
} satisfies RouteDefinition;

export default function BoardPage() {
  const params = useParams();
  const boardData = createAsync<BoardDetails | null>(() =>
    fetchBoard({ id: params.id })
  );
  const users = createAsync<UsersList>(() => listUsers());
  const allUsers = createAsync<UsersList>(() => listUsers());
  const allTags = createAsync<TagsList>(() => listTags());

  // Local mutable copy for optimistic updates
  const [board, setBoard] = createSignal<BoardDetails | null>(null);
  const [isAddCardModalOpen, setIsAddCardModalOpen] = createSignal(false);

  // Sync local state with server data
  createEffect(() => {
    const data = boardData();
    if (data) {
      setBoard(data);
    }
  });

  // Drag-and-drop handler using composable hook
  const { handleDragEnd } = useBoardDragDrop({ board, setBoard, boardData });

  // Handle optimistic card updates
  const handleCardUpdate = (cardId: string, updates: Partial<BoardCard>) => {
    const currentBoard = board();
    if (!currentBoard) return;

    const updatedBoard = {
      ...currentBoard,
      lists: currentBoard.lists.map((list) => ({
        ...list,
        cards: list.cards.map((card) =>
          card.id === cardId ? { ...card, ...updates } : card
        ),
      })),
    };

    setBoard(updatedBoard);
  };

  // Handle optimistic card creation
  const handleCardAdd = (cardData: {
    title: string;
    description: string | null;
    assigneeId: string | null;
    tagIds: string[];
  }) => {
    const currentBoard = board();
    if (!currentBoard) return;

    // Find the Todo list
    const todoList = currentBoard.lists.find((list) => list.title === "Todo");
    if (!todoList) return;

    // Create new card with optimistic data
    const newCard: BoardCard = {
      id: crypto.randomUUID(),
      title: cardData.title,
      description: cardData.description,
      assigneeId: cardData.assigneeId,
      position: todoList.cards.length,
      completed: false,
      tags: (allTags() || []).filter((tag) => cardData.tagIds.includes(tag.id)),
      comments: [],
    };

    const updatedBoard = {
      ...currentBoard,
      lists: currentBoard.lists.map((list) =>
        list.title === "Todo"
          ? { ...list, cards: [...list.cards, newCard] }
          : list
      ),
    };

    setBoard(updatedBoard);
  };

  return (
    <main class="w-full p-8 space-y-10 rounded-3xl bg-base-100 dark:bg-base-200 shadow-xl">
      <div class="breadcrumbs text-sm">
        <ul>
          <li>
            <A
              href="/"
              class="link link-hover"
            >
              Boards
            </A>
          </li>
          <li>
            <Show
              when={board()}
              fallback={<span>Loading...</span>}
            >
              {(data) => (
                <span class="text-base-content/60">{data().title}</span>
              )}
            </Show>
          </li>
        </ul>
      </div>

      <Show
        when={board()}
        keyed
        fallback={
          <div class="flex justify-center py-16">
            <span
              class="loading loading-spinner loading-lg text-primary"
              aria-label="Loading board"
            />
          </div>
        }
      >
        {(data: BoardDetails) => (
          <>
            <DragDropBoard
              onDragEnd={handleDragEnd}
              board={board}
            >
              <div class="space-y-8">
                <BoardOverview data={data} />

                <div class="flex justify-start mb-4">
                  <button
                    type="button"
                    class="btn btn-primary"
                    onClick={() => setIsAddCardModalOpen(true)}
                  >
                    Add Card
                  </button>
                </div>

                <section class="flex gap-7 overflow-x-auto pb-8">
                  <For
                    each={data.lists}
                    fallback={<CardListFallback />}
                  >
                    {(list) => (
                      <CardList
                        list={list}
                        users={users()}
                        allUsers={allUsers() || []}
                        allTags={allTags() || []}
                        onCardUpdate={handleCardUpdate}
                      />
                    )}
                  </For>
                </section>
              </div>
            </DragDropBoard>
            <AddCardModal
              boardId={data.id}
              users={allUsers() || []}
              tags={allTags() || []}
              isOpen={isAddCardModalOpen()}
              onClose={() => setIsAddCardModalOpen(false)}
              onCardAdd={handleCardAdd}
            />
          </>
        )}
      </Show>
    </main>
  );
}
