// kanban-tanstack-solid/src/components/AddBoardModal.tsx
import { createSignal } from "solid-js";
import { createBoard } from "../utils/api";
import { useRouter } from "@tanstack/solid-router";

export function AddBoardModal(props: {
  onBoardAdd?: (board: {
    id: string;
    title: string;
    description: string | null;
  }) => void;
}) {
  const [isOpen, setIsOpen] = createSignal(false);
  const [error, setError] = createSignal<string | null>(null);
  const [isSubmitting, setIsSubmitting] = createSignal(false);
  const router = useRouter();

  const handleSubmit = async (e: SubmitEvent) => {
    e.preventDefault();
    const form = e.currentTarget as HTMLFormElement;
    const formData = new FormData(form);

    setError(null);
    setIsSubmitting(true);

    try {
      const title = formData.get("title") as string;
      const description = formData.get("description") as string;

      // Wait for server response to get the real ID
      const result = await createBoard({
        data: {
          title,
          description: description || null,
        },
      });

      if (!result.success) {
        setError(result.error || "An error occurred");
        setIsSubmitting(false);
        return;
      }

      // Update UI with server-generated ID
      if (props.onBoardAdd && result.data) {
        props.onBoardAdd({
          id: result.data.id,
          title: result.data.title,
          description: result.data.description ?? null,
        });
      }

      setIsOpen(false);
      form.reset();
      router.invalidate();
    } catch {
      setError("An unexpected error occurred. Please try again.");
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <>
      <button
        type="button"
        class="btn btn-primary"
        onClick={() => setIsOpen(true)}
      >
        Add Board
      </button>

      {isOpen() && (
        <dialog
          class="modal modal-open !mt-0"
          onClick={(e) => {
            if (e.target === e.currentTarget) setIsOpen(false);
          }}
        >
          <div class="modal-backdrop bg-black/70" />
          <div class="modal-box bg-base-200 dark:bg-base-300">
            <form method="dialog" onSubmit={handleSubmit}>
              <button
                type="button"
                class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2"
                onClick={() => setIsOpen(false)}
              >
                ✕
              </button>
              <h3 class="font-bold text-lg mb-4">Add New Board</h3>

              {error() && (
                <div class="alert alert-error mb-4">
                  <span>{error()}</span>
                </div>
              )}

              <div class="form-control w-full mb-4">
                <label class="label">
                  <span class="label-text">Title</span>
                </label>
                <input
                  type="text"
                  name="title"
                  class="input input-bordered w-full"
                  placeholder="Enter board title"
                  required
                  disabled={isSubmitting()}
                />
              </div>

              <div class="form-control w-full mb-4">
                <label class="label">
                  <span class="label-text">Description</span>
                </label>
                <textarea
                  name="description"
                  class="textarea textarea-bordered h-24 w-full"
                  placeholder="Enter board description (optional)"
                  disabled={isSubmitting()}
                />
              </div>

              <div class="modal-action">
                <button
                  type="button"
                  class="btn btn-ghost"
                  onClick={() => setIsOpen(false)}
                  disabled={isSubmitting()}
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  class="btn btn-primary"
                  disabled={isSubmitting()}
                >
                  {isSubmitting() ? "Adding..." : "Add Board"}
                </button>
              </div>
            </form>
          </div>
        </dialog>
      )}
    </>
  );
}

// kanban-analog/src/app/components/modals/add-board-modal.component.ts
import { Component, signal, output, inject } from '@angular/core';
import { ApiService } from '../../../lib/api.service';
import type { BoardSummary } from '../../../lib/types';

@Component({
  selector: 'app-add-board-modal',
  imports: [],
  template: `
    <button type="button" class="btn btn-primary" (click)="isOpen.set(true)">
      Add Board
    </button>

    @if (isOpen()) {
      <dialog class="modal modal-open !mt-0" (click)="closeOnBackdrop($event)">
        <div class="modal-backdrop bg-black/70"></div>
        <div class="modal-box bg-base-200 dark:bg-base-300">
          <form (submit)="handleSubmit($event)">
            <button
              type="button"
              class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2"
              (click)="close()"
            >
              ✕
            </button>
            <h3 class="font-bold text-lg mb-4">Add New Board</h3>

            @if (error()) {
              <div class="alert alert-error mb-4">
                <span>{{ error() }}</span>
              </div>
            }

            <div class="form-control w-full mb-4">
              <label class="label">
                <span class="label-text">Title</span>
              </label>
              <input
                type="text"
                name="title"
                class="input input-bordered w-full"
                placeholder="Enter board title"
                required
                [disabled]="isSubmitting()"
              />
            </div>

            <div class="form-control w-full mb-4">
              <label class="label">
                <span class="label-text">Description</span>
              </label>
              <textarea
                name="description"
                class="textarea textarea-bordered h-24 w-full"
                placeholder="Enter board description (optional)"
                [disabled]="isSubmitting()"
              ></textarea>
            </div>

            <div class="modal-action">
              <button
                type="button"
                class="btn btn-ghost"
                (click)="close()"
                [disabled]="isSubmitting()"
              >
                Cancel
              </button>
              <button
                type="submit"
                class="btn btn-primary"
                [disabled]="isSubmitting()"
              >
                {{ isSubmitting() ? 'Adding...' : 'Add Board' }}
              </button>
            </div>
          </form>
        </div>
      </dialog>
    }
  `,
})
export class AddBoardModalComponent {
  private apiService = inject(ApiService);

  isOpen = signal(false);
  error = signal<string | null>(null);
  isSubmitting = signal(false);
  boardAdded = output<BoardSummary>();

  close() {
    this.isOpen.set(false);
    this.error.set(null);
  }

  closeOnBackdrop(event: MouseEvent) {
    if (event.target === event.currentTarget) {
      this.close();
    }
  }

  handleSubmit(event: SubmitEvent) {
    event.preventDefault();
    this.error.set(null);
    this.isSubmitting.set(true);

    const form = event.currentTarget as HTMLFormElement;
    const formData = new FormData(form);
    const title = formData.get('title') as string;
    const description = formData.get('description') as string;

    this.apiService
      .createBoard({
        title: title,
        description: description || null,
      })
      .subscribe({
        next: (result) => {
          if (result.success) {
            this.boardAdded.emit(result.data);
            form.reset();
            this.close();
          } else {
            this.error.set('Failed to create board');
          }
          this.isSubmitting.set(false);
        },
        error: (err) => {
          this.error.set('An unexpected error occurred. Please try again.');
          this.isSubmitting.set(false);
        },
      });
  }
}
