// kanban-tanstack/src/components/modals/CardEditModal.tsx
import { useState, useEffect } from "react";
import type { BoardCard, UsersList, TagsList } from "../lib/api";
import { updateCard, deleteCard } from "../../utils/api";

export function CardEditModal({
  card,
  users,
  tags,
  isOpen,
  onClose,
  onUpdate,
  onDelete,
}: {
  card: BoardCard;
  users: UsersList;
  tags: TagsList;
  isOpen: boolean;
  onClose: () => void;
  onUpdate?: (updatedCard: Partial<BoardCard>) => void;
  onDelete?: () => void;
}) {
  const [selectedTagIds, setSelectedTagIds] = useState<Set<string>>(
    new Set(card.tags.map((t) => t.id))
  );
  const [isDeleting, setIsDeleting] = useState(false);

  // Reset selected tags when card changes
  useEffect(() => {
    setSelectedTagIds(new Set(card.tags.map((t) => t.id)));
  }, [card]);

  const toggleTag = (tagId: string) => {
    const newSet = new Set(selectedTagIds);
    if (newSet.has(tagId)) {
      newSet.delete(tagId);
    } else {
      newSet.add(tagId);
    }
    setSelectedTagIds(newSet);
  };

  const handleDelete = async () => {
    if (!confirm("Are you sure you want to delete this card?")) {
      return;
    }

    setIsDeleting(true);

    try {
      const result = await deleteCard({ data: card.id });

      if (result.success) {
        if (onDelete) {
          onDelete();
        }
        onClose();
      } else {
        alert(result.error || "Failed to delete card");
        setIsDeleting(false);
      }
    } catch (error) {
      alert("Failed to delete card. Please try again.");
      setIsDeleting(false);
    }
  };

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const form = e.currentTarget;
    const formData = new FormData(form);

    const title = formData.get("title") as string;
    const description = formData.get("description") as string;
    const assigneeId = formData.get("assigneeId") as string;

    // Optimistically update the UI
    if (onUpdate) {
      const updatedTags = tags.filter((tag) => selectedTagIds.has(tag.id));
      onUpdate({
        title,
        description: description || null,
        assigneeId: assigneeId || null,
        tags: updatedTags,
      });
    }

    onClose();

    // Persist to server in background
    await updateCard({
      data: {
        cardId: card.id,
        title,
        description: description || null,
        assigneeId: assigneeId || null,
        tagIds: Array.from(selectedTagIds),
      },
    });
  };

  if (!isOpen) return null;

  return (
    <dialog
      className="modal modal-open !mt-0"
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
    >
      <div className="modal-backdrop bg-black/70" />
      <div className="modal-box bg-base-200 dark:bg-base-300">
        <form method="dialog" onSubmit={handleSubmit}>
          <button
            type="button"
            className="btn btn-sm btn-circle btn-ghost absolute right-2 top-2"
            onClick={onClose}
          >
            ✕
          </button>
          <h3 className="font-bold text-lg mb-4">Edit Card</h3>

          <input type="hidden" name="cardId" value={card.id} />

          <div className="form-control w-full mb-4">
            <label className="label">
              <span className="label-text">Title</span>
            </label>
            <input
              type="text"
              name="title"
              className="input input-bordered w-full"
              defaultValue={card.title}
              required
            />
          </div>

          <div className="form-control w-full mb-4">
            <label className="label">
              <span className="label-text">Description</span>
            </label>
            <textarea
              name="description"
              className="textarea textarea-bordered h-24 w-full"
              defaultValue={card.description || ""}
            />
          </div>

          <div className="form-control w-full mb-4">
            <label className="label">
              <span className="label-text">Assignee</span>
            </label>
            <select
              name="assigneeId"
              className="select select-bordered w-full"
              defaultValue={card.assigneeId || ""}
            >
              <option value="">Unassigned</option>
              {users.map((user) => (
                <option key={user.id} value={user.id}>
                  {user.name}
                </option>
              ))}
            </select>
          </div>

          <div className="form-control w-full mb-4">
            <label className="label">
              <span className="label-text">Tags</span>
            </label>
            <div className="flex flex-wrap gap-2 p-4 border border-base-300 rounded-lg">
              {tags.map((tag) => (
                <button
                  key={tag.id}
                  type="button"
                  className={`badge border-2 font-semibold cursor-pointer transition-all hover:scale-105 ${
                    selectedTagIds.has(tag.id) ? "text-white" : "badge-outline"
                  }`}
                  style={
                    selectedTagIds.has(tag.id)
                      ? {
                          backgroundColor: tag.color,
                          borderColor: tag.color,
                        }
                      : {
                          color: tag.color,
                          borderColor: tag.color,
                        }
                  }
                  onClick={() => toggleTag(tag.id)}
                >
                  {tag.name}
                </button>
              ))}
            </div>
          </div>

          <div className="modal-action justify-between">
            <button
              type="button"
              className="btn btn-error"
              onClick={handleDelete}
              disabled={isDeleting}
            >
              {isDeleting ? "Deleting..." : "Delete Card"}
            </button>
            <div className="flex gap-2">
              <button type="button" className="btn btn-ghost" onClick={onClose}>
                Cancel
              </button>
              <button type="submit" className="btn btn-primary">
                Save Changes
              </button>
            </div>
          </div>
        </form>
      </div>
    </dialog>
  );
}

// kanban-analog/src/app/components/modals/card-edit-modal.component.ts
import {
  Component,
  signal,
  output,
  input,
  inject,
  effect,
} from '@angular/core';
import { ApiService } from '../../../lib/api.service';
import type { BoardCard, UsersList, TagsList } from '../../../lib/types';

@Component({
  selector: 'app-card-edit-modal',
  template: `
    @if (isOpen()) {
      <dialog class="modal modal-open !mt-0" (click)="closeOnBackdrop($event)">
        <div class="modal-backdrop bg-black/70"></div>
        <div class="modal-box bg-base-200 dark:bg-base-300">
          <form (submit)="handleSubmit($event)">
            <button
              type="button"
              class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2"
              (click)="close()"
            >
              ✕
            </button>
            <h3 class="font-bold text-lg mb-4">Edit Card</h3>

            <div class="form-control w-full mb-4">
              <label class="label"><span class="label-text">Title</span></label>
              <input
                type="text"
                name="title"
                class="input input-bordered w-full"
                required
                [value]="card().title"
                [disabled]="isDeleting()"
              />
            </div>

            <div class="form-control w-full mb-4">
              <label class="label"
                ><span class="label-text">Description</span></label
              >
              <textarea
                name="description"
                class="textarea textarea-bordered h-24 w-full"
                required
                [value]="card().description"
                [disabled]="isDeleting()"
              ></textarea>
            </div>

            <div class="form-control w-full mb-4">
              <label class="label"
                ><span class="label-text">Assignee</span></label
              >
              <select
                name="assigneeId"
                class="select select-bordered w-full"
                required
                [disabled]="isDeleting()"
              >
                <option disabled>Select an assignee</option>
                @for (user of users(); track user.id) {
                  <option [value]="user.id">{{ user.name }}</option>
                }
              </select>
            </div>

            <div class="form-control w-full mb-4">
              <label class="label"><span class="label-text">Tags</span></label>
              <div
                class="flex flex-wrap gap-2 p-4 border border-base-300 rounded-lg"
              >
                @for (tag of tags(); track tag.id) {
                  <button
                    type="button"
                    class="badge border-2 font-semibold cursor-pointer transition-all hover:scale-105"
                    [class.text-white]="selectedTagIds().has(tag.id)"
                    [class.badge-outline]="!selectedTagIds().has(tag.id)"
                    [style.backgroundColor]="
                      selectedTagIds().has(tag.id) ? tag.color : ''
                    "
                    [style.borderColor]="tag.color"
                    [style.color]="
                      !selectedTagIds().has(tag.id) ? tag.color : ''
                    "
                    (click)="toggleTag(tag.id)"
                  >
                    {{ tag.name }}
                  </button>
                }
              </div>
            </div>

            <div class="modal-action justify-between">
              <button
                type="button"
                class="btn btn-error"
                (click)="handleDelete()"
                [disabled]="isDeleting()"
              >
                {{ isDeleting() ? 'Deleting...' : 'Delete Card' }}
              </button>
              <div class="flex gap-2">
                <button
                  type="button"
                  class="btn btn-ghost"
                  (click)="close()"
                  [disabled]="isDeleting()"
                >
                  Cancel
                </button>
                <button type="submit" class="btn btn-primary">
                  Save Changes
                </button>
              </div>
            </div>
          </form>
        </div>
      </dialog>
    }
  `,
})
export class CardEditModalComponent {
  private apiService = inject(ApiService);

  card = input.required<BoardCard>();
  users = input.required<UsersList>();
  tags = input.required<TagsList>();
  isOpen = input.required<boolean>();
  onClose = output<void>();
  cardUpdated = output<Partial<BoardCard>>();
  cardDeleted = output<void>();

  selectedTagIds = signal<Set<string>>(new Set());
  isDeleting = signal(false);

  constructor() {
    effect(() => {
      const card = this.card();
      this.selectedTagIds.set(new Set(card.tags.map((t) => t.id)));
    });
  }

  handleDelete() {
    if (!confirm('Are you sure you want to delete this card?')) {
      return;
    }

    this.isDeleting.set(true);

    this.apiService.deleteCard(this.card().id).subscribe({
      next: (result) => {
        if (result.success) {
          this.cardDeleted.emit();
          this.close();
        } else {
          alert(result.error || 'Failed to delete card');
          this.isDeleting.set(false);
        }
      },
      error: (err) => {
        alert('Failed to delete card. Please try again.');
        this.isDeleting.set(false);
      },
    });
  }

  close() {
    this.onClose.emit();
  }

  closeOnBackdrop(event: MouseEvent) {
    if (event.target === event.currentTarget) {
      this.close();
    }
  }

  toggleTag(tagId: string) {
    const newSet = new Set(this.selectedTagIds());
    if (newSet.has(tagId)) {
      newSet.delete(tagId);
    } else {
      newSet.add(tagId);
    }
    this.selectedTagIds.set(newSet);
  }

  handleSubmit(event: SubmitEvent) {
    event.preventDefault();

    const updatedTags = this.tags().filter((tag) =>
      this.selectedTagIds().has(tag.id),
    );

    const form = event.currentTarget as HTMLFormElement;
    const formData = new FormData(form);
    const title = formData.get('title') as string;
    const description = formData.get('description') as string;
    const assigneeId = formData.get('assigneeId') as string;

    // Optimistic update
    this.cardUpdated.emit({
      title: title,
      description: description || null,
      assigneeId: assigneeId || null,
      tags: updatedTags,
    });

    this.close();

    // Persist to server
    this.apiService
      .updateCard({
        cardId: this.card().id,
        title: title,
        description: description || null,
        assigneeId: assigneeId || null,
        tagIds: Array.from(this.selectedTagIds()),
      })
      .subscribe();
  }
}
