// kanban-tanstack/src/components/BoardOverview.tsx

import type { BoardDetails } from "../lib/api";
import { BarChart } from "./charts/BarChart";
import { PieChart } from "./charts/PieChart";

export function BoardOverview({ data }: { data: BoardDetails }) {
  // DaisyUI pastel colors matching the theme
  const pastelColors = [
    "#fbbf24", // amber (warning)
    "#f472b6", // pink (secondary)
    "#a78bfa", // purple (primary)
    "#60a5fa", // blue (info)
  ];

  // Prepare data for charts
  const chartData = data.lists.map((list) => ({
    label: list.title,
    value: list.cards.length,
  }));

  return (
    <section className="bg-base-200 dark:bg-base-300 shadow-xl rounded-3xl p-8 space-y-6">
      {/* Header Section */}
      <div className="space-y-3">
        <div className="badge badge-secondary badge-outline">Board overview</div>
        <h1 className="text-4xl font-black text-primary">{data.title}</h1>
        {data.description && (
          <p className="text-base text-base-content/60 max-w-2xl">
            {data.description}
          </p>
        )}
      </div>

      {/* Charts Section */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-12 md:gap-6 max-w-[1190px] mx-auto items-start">
        <BarChart
          data={chartData}
          colors={pastelColors}
          title="Cards per List"
        />
        <PieChart
          data={chartData}
          colors={pastelColors}
          title="Distribution"
        />
      </div>
    </section>
  );
}

// kanban-qwikcity/src/components/BoardOverview.tsx
import { component$, useComputed$ } from "@builder.io/qwik";
import type { BoardDetails } from "~/db/queries";
import { BarChart } from "./charts/BarChart";
import { PieChart } from "./charts/PieChart";

interface BoardOverviewProps {
  data: BoardDetails;
}

export const BoardOverview = component$<BoardOverviewProps>(({ data }) => {

  // DaisyUI pastel colors matching the theme
  const pastelColors = [
    "#fbbf24", // amber (warning)
    "#f472b6", // pink (secondary)
    "#a78bfa", // purple (primary)
    "#60a5fa", // blue (info)
  ];

  // Prepare data for charts - use useComputed$ to make it reactive
  const chartData = useComputed$(() => {
    return data.lists.map((list) => ({
      label: list.title,
      value: list.cards.length,
    }));
  });

  return (
    <section class="bg-base-200 dark:bg-base-300 shadow-xl rounded-3xl p-8 space-y-6">
      {/* Header Section */}
      <div class="space-y-3">
        <div class="badge badge-secondary badge-outline">Board overview</div>
        <h1 class="text-4xl font-black text-primary">{data.title}</h1>
        {data.description && (
          <p class="text-base text-base-content/60 max-w-2xl">
            {data.description}
          </p>
        )}
      </div>

      {/* Charts Section */}
      <div class="grid grid-cols-1 md:grid-cols-2 gap-12 md:gap-6 max-w-[1190px] mx-auto items-start">
        <BarChart
          data={chartData.value}
          colors={pastelColors}
          title="Cards per List"
        />
        <PieChart
          data={chartData.value}
          colors={pastelColors}
          title="Distribution"
        />
      </div>
    </section>
  );
});
